version: ‘3.8’
services:
  backend:
    build:
      # backend앱의 빌드 컨텍스트 위치 지정
      context: ./order_server
      dockerfile: Dockerfile
    # 재 시도 횟수 지정하기
    restart: on-failure:10
    ports:
      - “8082:8082”
    environment:
    # docker-compose 안에 프론트랑 백이 다 있어서  프론트의 db안에 있는 mydb로 가능
    # docker-compose로 네트워크를 결합하였기 때문에 mydb라는 서비스명으로 host호출 가능
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mydb:3306/order_system
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    volumes:
    # docker-compose의 특정경로의 image-path라는 이름으로 /tmp와 매핑
      - image-path:/tmp
      # 직접 경로 매핑
      # - /Users/jang-eunji/Desktop/tmp:/tmp
    depends_on:
    #  mydb가 먼저 생성된 이후에 backend를 생성하겠다라는 선언
      - mydb
  frontend:
    build:
        context: ./ordering-front
        dockerfile: Dockerfile
    ports:
      - “8081:8081"
  mydb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=ordersys
volumes:
  image-path: